//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AnonymousUserId { get; set; }
        public double TotalAmount { get; set; }
        public string Code { get; set; }
    
        public virtual AnonymousUser AnonymousUser { get; set; }
        public virtual User User { get; set; }
    }
}
