//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ID { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string Code { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Product Product { get; set; }
    }
}
